#!/usr/bin/python

import sys

def usage():
  print("{} <width> <height> <filename>".format(sys.argv[0]))
  sys.exit(-1)

if __name__ == "__main__":

  if len(sys.argv) < 4:
    usage()

  width = int(sys.argv[1])
  height = int(sys.argv[2])
  filename = sys.argv[3]

  header = "P5\n{} {}\n255\n".format(str(width), str(height))
  data = bytearray(width * height)

  with open(filename, "w") as fd:
    fd.write(header)
    fd.write(data)
